djangotut1/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),               
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'polls'
'''
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]
'''
urlpatterns = [
    url(r'^$', views.home_view, name='home'),
    url(r'^list/$', views.PollsView.as_view(), name='polls'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^accounts/login/$', auth_views.login, {'template_name':'polls/login.html'}, name='login'),
    url(r'^accounts/logout/$', views.logout_view, name='logout'),
    url(r'^upload_file/$', views.upload_file_view, name='upload_file'),
    url(r'^upload_success/$', views.upload_success_view, name='upload_success'),
    ]

polls/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
import datetime
from django.utils import timezone

# Create your models here.
@python_2_unicode_compatible 
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)        

@python_2_unicode_compatible 
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

polls/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.utils.decorators import method_decorator
from django.views import generic

from .models import Question, Choice
from .forms import UploadFileForm
from .utils import handle_uploaded_file

# Create your views here.
'''
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})
'''

@method_decorator(login_required, name='dispatch')
class PollsView(generic.ListView):
    template_name = 'polls/polls.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

@method_decorator(login_required, name='dispatch')
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

@method_decorator(login_required, name='dispatch')
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def logout_view(request):
    logout(request)
    # Redirect to a success page.
    return HttpResponseRedirect(reverse('polls:login'))

@login_required
def upload_file_view(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES['file'])
            return HttpResponseRedirect(reverse('polls:upload_success'))
    else:
        form = UploadFileForm()
    return render(request, 'polls/upload_file.html', {'form': form})

@login_required
def upload_success_view(request):
    return render(request, 'polls/upload_success.html')

@login_required
def home_view(request):
    return render(request, 'polls/home.html')

polls/templates/polls/base.html
<html>
<head>
{% load staticfiles %}
<!--link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}"-->
<!--script src="{% static 'js/jquery.min.js' %}"></script-->
<!--script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script-->
</head>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'polls:home' %}">Home</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'polls:polls' %}">Polls</a>
                </li>
                <li>
                    <a href="{% url 'polls:upload_file' %}">Upload Files</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if not user.is_authenticated %}
                <li>
                <a href="{% url 'polls:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a>
                </li>
                {% else %}
                <li>
                <a href="{% url 'polls:logout' %}"><span class="glyphicon glyphicon-logout"></span> Logout</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>        
</nav>
{% if user.is_authenticated %}
<p>Welcome, {{ user.username }}</p>
{% endif %}    

{% block content %}
{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
<link rel="shortcut icon" href="{% static 'img/favicon/favicon.ico' %}"/>

</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}

<div class="main-center">
    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
        {% endfor %}
        <input type="submit" value="Vote" />
    </form>
</div>
{% endblock %}

polls/templates/polls/home.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="main-center">
    <h1>Home page</h1>
</div>
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="main-center">
    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
</div>
{% endblock %}

polls/templates/polls/login.html
{% extends "polls/base.html" %}

{% block content %}

<div class="container">
    <div class="main-login main-center">
        {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
        {% endif %}

        {% if next %}
        {% if user.is_authenticated %}
        <p>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p>
        {% else %}
        <p>Please login to see this page.</p>
        {% endif %}
        {% endif %}

        <form class="form-horizontal" method="post" action="{% url 'polls:login' %}">
            {% csrf_token %}
            <table>
                <tr>
                    <td>{{ form.username.label_tag }}</td>
                    <td>{{ form.username }}</td>
                </tr>
                <tr>
                    <td>{{ form.password.label_tag }}</td>
                    <td>{{ form.password }}</td>
                </tr>
            </table>

            <input type="submit" value="login" />
            <input type="hidden" name="next" value="{{ next }}" />
        </form>

        {# Assumes you setup the password_reset view in your URLconf #}

    </div>
</div>
{% endblock %}

polls/templates/polls/logout.html
{% extends "polls/base.html" %}

{% block content %}

<p>Your have been logged out.</p>

{% endblock %}

polls/templates/polls/polls.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="main-center">
    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
</div>
{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}

<div class="main-center">
    <h1>{{ question.question_text }}</h1>

    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</div>
{% endblock %}

polls/templates/polls/upload_file.html
{% extends "polls/base.html" %}

{% block content %}

<style>
.main-center{
    margin-top: 30px;
    margin: 0 auto;
    max-width: 330px;
    padding: 40px 40px;

}
</style>
<div class="container">
    <div class="main-center">
        {% if form.errors %}
        <p>Upload failed. Please try again.</p>
        {% endif %}

        <form class="form-horizontal" method="post" action="{% url 'polls:upload_file' %}" enctype="multipart/form-data">
            {% csrf_token %}
			{{ form.as_table }}
            <input type="submit" value="Upload" />
        </form>

    </div>
</div>
{% endblock %}

polls/templates/polls/upload_success.html
{% extends "polls/base.html" %}

{% block content %}

<p>File uploaded successfully.</p>

{% endblock %}